window.itensDatabase = [
    {
        id: 1,
        tipo: 'hotel',
        nome: 'Hotel Avenida Palace',
        destino: 'Lisboa, Portugal',
        estrelas: '5',
        preco: 195,
        capacidadeMax: 4,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Avenida da Liberdade • 0,5 km do centro',
        comodidades: 'Wi-Fi gratuito • Piscina • Spa • Restaurante',
        imagem: 'images/avenida-palace.webp',
        destaque: true,
        textoBotao: 'Reservar'
    },
    {
        id: 2,
        tipo: 'hotel',
        nome: 'Hotel Bairro Alto',
        destino: 'Lisboa, Portugal',
        estrelas: '4',
        preco: 145,
        capacidadeMax: 3,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Chiado • 1,2 km do centro',
        comodidades: 'Wi-Fi gratuito • Bar • Vista cidade • Animais permitidos',
        imagem: 'images/bairro-alto.webp',
        destaque: false,
        textoBotao: 'Reservar'
    },
    {
        id: 3,
        tipo: 'hotel',
        nome: 'Residencial Rossio',
        destino: 'Lisboa, Portugal',
        estrelas: '3',
        preco: 55,
        capacidadeMax: 2,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Baixa • Centro histórico',
        comodidades: 'Wi-Fi gratuito • Pequeno-almoço incluído • Ar condicionado',
        imagem: 'images/rossio.jpg',
        destaque: false,
        textoBotao: 'Reservar'
    },
    {
        id: 4,
        tipo: 'hotel',
        nome: 'Pestana CR7 Lisboa',
        destino: 'Lisboa, Portugal',
        estrelas: '4',
        preco: 130,
        capacidadeMax: 2,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Rua do Comércio • 0,3 km do centro',
        comodidades: 'Wi-Fi gratuito • Ginásio • Bar Desportivo',
        imagem: 'images/pestana-cr7.webp',
        destaque: true,
        textoBotao: 'Reservar'
    },
    {
        id: 5,
        tipo: 'hotel',
        nome: 'Tivoli Avenida Liberdade',
        destino: 'Lisboa, Portugal',
        estrelas: '5',
        preco: 260,
        capacidadeMax: 4,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Avenida da Liberdade • 0,8 km do centro',
        comodidades: 'Piscina Exterior • Sky Bar • Spa de Luxo',
        imagem: 'images/tivoli.jpg',
        destaque: true,
        textoBotao: 'Reservar'
    },
    {
        id: 6,
        tipo: 'hotel',
        nome: 'Selina Secret Garden',
        destino: 'Lisboa, Portugal',
        estrelas: '3',
        preco: 42,
        capacidadeMax: 2,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Cais do Sodré • 1,5 km do centro',
        comodidades: 'Wi-Fi gratuito • Piscina • Cozinha partilhada',
        imagem: 'images/selina.webp',
        destaque: false,
        textoBotao: 'Reservar'
    },
    {
        id: 7,
        tipo: 'hotel',
        nome: 'Hotel Mundial',
        destino: 'Lisboa, Portugal',
        estrelas: '4',
        preco: 98,
        capacidadeMax: 3,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Martim Moniz • 0,1 km do centro',
        comodidades: 'Rooftop Bar • Estacionamento Grátis',
        imagem: 'images/mundial.jpg',
        destaque: false,
        textoBotao: 'Reservar'
    },
    {
        id: 8,
        tipo: 'hotel',
        nome: 'Myriad by SANA',
        destino: 'Lisboa, Portugal',
        estrelas: '5',
        preco: 310,
        capacidadeMax: 4,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Lisboa, Parque das Nações • Frente ao Rio',
        comodidades: 'Vista Panorâmica • Spa • Restaurante Michelin',
        imagem: 'images/myriad.jpg',
        destaque: true,
        textoBotao: 'Reservar'
    },
    {
        id: 9,
        tipo: 'voo',
        nome: 'TAP Air Portugal (LIS ✈ BCN)',
        origem: 'Lisboa, Portugal',
        destino: 'Barcelona, Espanha',
        estrelas: 'voo',
        preco: 89,
        capacidadeMax: 120,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Voo LIS ➝ BCN • Direto',
        comodidades: 'Bagagem de mão • Refeição a bordo',
        imagem: 'images/Sagrada.jpg',
        destaque: true,
        textoBotao: 'Selecionar'
    },
    {
        id: 10,
        tipo: 'voo',
        nome: 'Ryanair (MAD ✈ LIS)',
        origem: 'Madrid, Espanha',
        destino: 'Lisboa, Portugal',
        estrelas: 'voo',
        preco: 35,
        capacidadeMax: 160,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Voo MAD ➝ LIS • Económico • Direto',
        comodidades: 'Artigo pessoal pequeno',
        imagem: 'images/ryanair.webp',
        destaque: false,
        textoBotao: 'Selecionar'
    },
    {
        id: 12,
        tipo: 'voo',
        nome: 'EasyJet (LIS ✈ PAR)',
        origem: 'Lisboa, Portugal',
        destino: 'Paris, França',
        estrelas: 'voo',
        preco: 72,
        capacidadeMax: 150,
        disponivelDe: '2026-01-01',
        disponivelAte: '2026-12-31',
        localizacao: 'Voo LIS ➝ PAR • Direto',
        comodidades: 'Bagagem de mão • Lugar standard',
        imagem: 'images/easyjet.jpg',
        destaque: false,
        textoBotao: 'Selecionar'
    },
    {
        id: 11,
        tipo: 'evento',
        nome: 'Festival NOS Alive',
        destino: 'Lisboa, Portugal',
        estrelas: 'evento',
        preco: 75,
        capacidadeMax: 5000,
        disponivelDe: '2026-07-09',
        disponivelAte: '2026-07-11',
        localizacao: 'Lisboa, Passeio Marítimo de Algés',
        comodidades: 'Bilhete geral • Música ao vivo • Entrada diária',
        imagem: 'images/festivalnos.jpg',
        destaque: true,
        textoBotao: 'Comprar bilhete'
    }
];